# Site settings
title: Giovanna Lomanto
email: gglomanto@gmail.com
url: https://gglomanto.github.io
description: "Giovanna Lomanto is a California native currently pursuing her Bachelor of Arts in English at the University of California, Berkeley. When not writing her thesis, she is often busy working as a Program Associate and Teaching Artist at a made-in-Oakland creative writing center, Chapter 510 & the Dept. of Make Believe. She has recently worked at the UC Press and the Berkeley Student Cooperative."
keywords: "author poet writer uc berkeley"
skills: ""
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#  - static : #pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: aad6ef #80B3FF
  primary-rgb: "170, 214, 239" #"128,179,255"
  secondary:  5e927a #FD6E8A
  secondary-dark: 925e76  #A2122F

# Footer settings
footer:
  # copyright: Dr. Henry Jekyll
  location: location
  social: connect with me
  credits: credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/giovanna_lomanto
  - title: twitter
    url: http://twitter.com/littlelomanto
  - title: facebook
    url: \# # http://facebook.com/giovanna_lomanto TODO

# Postal address (add as many lines as necessary)
address:
  - line: the universe, the milky way galaxy
  - line: the solar system, jupiter

# Credits content
credits: '<a href="https://jekyllthemes.io/theme/freelancer-theme">freelancer theme</a>, maintained by <a href="http://adjchen.com">mighty chen</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
